vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Jun 2012 20:08:14 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|Style/crep.html Featured/featured.html Buyer/TitleEscrow/title.html Search/Standard.html Buyer/Homeowners/environmental.html ContactMe/market.html Buyer/TitleEscrow/required.html Buyer/TipsSellers/considering.html Buyer/MortgageInfo/basic.html Buyer/MortgageInfo/brief.html Buyer/TitleEscrow/functions.html Buyer/TitleEscrow/statements.html Buyer/TipsBuyers/thinking.html Buyer/MortgageInfo/bi.html Buyer/TitleEscrow/creative.html Buyer/TitleEscrow/understanding.html Buyer/TipsSellers/for.html Buyer/TipsBuyers/build.html Blog/blog.html Buyer/MortgageInfo/items.html Buyer/Homeowners/mello.html Buyer/TipsSellers/know.html Buyer/TipsSellers/what.html Buyer/MortgageInfo/mortgage.html Featured/open.html Buyer/TipsSellers/plan.html Buyer/MortgageInfo/no.html Buyer/Homeowners/condominium.html ContactMe/dream.html AboutMe/about.html Buyer/mortgage.html Style/index.dwt Featured/featured1.html Buyer/TipsSellers/setting.html Buyer/TipsBuyers/finding.html Buyer/TipsBuyers/is.html Buyer/TipsSellers/making.html Buyer/TipsBuyers/avoiding.html Buyer/TipsBuyers/use.html Buyer/MortgageInfo/documenting.html Buyer/MortgageInfo/where.html Search/search.html Buyer/relocation.html Buyer/TipsSellers/insist.html Buyer/TipsBuyers/getting.html Buyer/TipsBuyers/Importance.html Buyer/TipsBuyers/why.html Buyer/MortgageInfo/closing.html Buyer/MortgageInfo/land.html Buyer/Homeowners/lead.html Buyer/Homeowners/radon.html Buyer/Homeowners/underground.html Buyer/buyer.html ContactMe/contact.html Featured/featured2.php Buyer/MortgageInfo/advantages.html Buyer/MortgageInfo/savings.html Buyer/Homeowners/understanding.html Buyer/TitleEscrow/refinancing.html Buyer/TipsSellers/finding.html Buyer/MortgageInfo/pros.html Buyer/MortgageInfo/types.html Buyer/Homeowners/common.html Buyer/TitleEscrow/requirements.html Buyer/TitleEscrow/where.html Buyer/TipsSellers/getting.html Buyer/Real/glossary.html Buyer/MortgageInfo/arm.html Buyer/Homeowners/living.html Search/Map.html Buyer/weather.html Buyer/TitleEscrow/closing.html Buyer/TitleEscrow/why.html Buyer/TipsBuyers/hot.html Buyer/MortgageInfo/fico.html Buyer/Homeowners/mechanic.html index.html Buyer/demographic.html Buyer/schools.html
vti_author:SR|Tracy-PC\\Tracy
vti_modifiedby:SR|Tracy-PC\\Tracy
vti_timecreated:TR|14 Jun 2012 20:08:14 -0000
vti_cacheddtm:TX|14 Jun 2012 20:08:14 -0000
vti_filesize:IR|2496
vti_syncwith_tracyrealestate.us\:21:TX|14 Jun 2012 20:08:14 -0000
vti_syncofs_tracyrealestate.us\:21:TW|20 Jun 2012 13:00:07 -0000
